modLoader="javafml"
loaderVersion="[28,)"
issueTrackerURL="https://github.com/ProjectEssentials/ProjectEssentials-Protect/issues"

[[mods]]
    modId="project_essentials_protect"
    version="${file.jarVersion}"
    displayName="Project Essentials Protect"
    updateJSONURL="https://raw.githubusercontent.com/ProjectEssentials/ProjectEssentials-Protect/MC-1.14.4/update.json"
    displayURL="https://github.com/ProjectEssentials/ProjectEssentials-Protect"
    credits="hujle, Mr Pikachu, JetBrains, all forge developers, and other contributors"
    authors="MairwunNx (Pavel Erokhin)"
    description='''
    Will written later.
    '''

[[dependencies.projectessentialsprotect]]
    modId="project_essentials_core"
    mandatory=true
    versionRange="[2,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.projectessentialsprotect]]
    modId="worldedit"
    mandatory=true
    versionRange="[7,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.projectessentialsprotect]]
    modId="forge"
    mandatory=true
    versionRange="[28,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.projectessentialsprotect]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4]"
    ordering="NONE"
    side="BOTH"
